package com.platform.analyzer.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * DTO for the Ollama {@code /api/generate} endpoint response body.
 *
 * <p>Only the {@code response} field is mapped — it contains the raw text
 * generated by the model (expected to be a JSON string conforming to
 * {@code specs/schemas/ai-analysis.v1.json}).
 * All other Ollama metadata fields (timings, context, etc.) are ignored.
 *
 * @param response The raw text output produced by the model.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record OllamaResponse(String response) {}
