import type { Config } from 'tailwindcss';

const config: Config = {
  prefix: 'kd-',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#0e1511',
        'surface-dim': '#0e1511',
        'surface-bright': '#343b36',
        'surface-container-lowest': '#09100c',
        'surface-container-low': '#161d19',
        'surface-container': '#1a211d',
        'surface-container-high': '#242c27',
        'surface-container-highest': '#2f3632',
        'on-surface': '#dde4dd',
        'on-surface-variant': '#bbcabf',
        'inverse-surface': '#dde4dd',
        'inverse-on-surface': '#2b322d',
        'surface-tint': '#4edea3',
        'surface-variant': '#2f3632',
        primary: '#4edea3',
        'on-primary': '#003824',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        'inverse-primary': '#006c49',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        'on-primary-fixed': '#002113',
        'on-primary-fixed-variant': '#005236',
        secondary: '#ffb2b7',
        'on-secondary': '#67001b',
        'secondary-container': '#b50036',
        'on-secondary-container': '#ffc2c4',
        'secondary-fixed': '#ffdadb',
        'secondary-fixed-dim': '#ffb2b7',
        'on-secondary-fixed': '#40000d',
        'on-secondary-fixed-variant': '#92002a',
        tertiary: '#ffb95f',
        'on-tertiary': '#472a00',
        'tertiary-container': '#e29100',
        'on-tertiary-container': '#523200',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        outline: '#86948a',
        'outline-variant': '#3c4a42',
        background: '#0e1511',
        'on-background': '#dde4dd',
        'ai-violet': '#a78bfa',
      },
      keyframes: {
        'pulse-soft': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.7', transform: 'scale(0.95)' },
        },
        reveal: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        flicker: {
          '0%, 19.999%, 22%, 62.999%, 64%, 64.999%, 70%, 100%': { opacity: '1' },
          '20%, 21.999%, 63%, 63.999%, 65%, 69.999%': { opacity: '0.96' },
        },
      },
      animation: {
        'pulse-soft': 'pulse-soft 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        reveal: 'reveal 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        shimmer: 'shimmer 2s linear infinite',
        flicker: 'flicker 4s linear infinite',
      },
      fontFamily: {
        'display-metrics': ['JetBrains Mono'],
        'headline-sm': ['Inter'],
        'body-md': ['Inter'],
        'code-sm': ['JetBrains Mono'],
        'label-caps': ['Inter'],
      },
      fontSize: {
        'display-metrics': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'code-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '18px', letterSpacing: '0.03em', fontWeight: '600' }],
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        margin: '16px',
        'container-padding': '24px',
      },
    },
  },
  plugins: [],
};

export default config;
